### PR TITLE
behold, the MEOW license

### PR DESCRIPTION
**Pull request by MikeDev101**

### CODE REVIEW

**Comment by TermOfficial** [comment]
this is crazy

**Comment by JoshAtticus** [comment]
why

**Comment by MikeDev101** [comment]
image

**Comment by JoshAtticus** [comment]
> image

**hurt us

**Comment by JoshAtticus** [comment]
Literally aged like milk

**Comment by CST1229** [comment]
> Literally aged like milk

r/agedlikemilk

**Comment by MikeDev101** [comment]
Locking for off topic

**Pull request merged**
