### PR TITLE
merge username selection using bluelist

### PR DESCRIPTION
**Pull request by Pixelation-Creations**

### CODE REVIEW

**Comment by MikeDev101** [comment]
file fails to load in https://turbowarp.org/editor?extension=https://mikedev101.github.io/cloudlink/B3-0.js&fps=60&hqpen, according to logs "gui Failed to unzip and extract project.json, with error: {}"

**Comment by Pixelation-Creations** [comment]
?? lemme see

**Comment by MikeDev101** [comment]
Temporarily keeping this pull request on hold since source code still fails to load. Are you sure you didn't add anything new to the extensions list?

**Comment by MikeDev101** [comment]
closing as this discussion has gone stale.

**Pull request closed without merging**
